/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Clases.Camino;
import Clases.Ciudad;
import Clases.ListaCaminos;
import Clases.ListaCiudad;
import Funciones.Global;
import javax.swing.JOptionPane;
import Clases.ListaCiudad;
import Clases.NodoCiudad;
import Funciones.Global;


/**
 *
 * @author Jose
 */
public class Ventana4 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana4
     */
    ListaCiudad listaciudad = Global.getListaciudades();
    ListaCaminos listacaminos = Global.getListacaminos();
    public Ventana4() {
        initComponents();
        // inidicarle al usuario la ciudad a agregar
        NodoCiudad aux = listaciudad.getHead();
        while(aux != null){
            String numero = Integer.toString(aux.getElement().getName());
            ciudadConectar.addItem("Ciudad: "+numero);
            aux = aux.getNext();
        }
        NodoCiudad aux2 = listaciudad.getHead();
        while (aux2.getNext()!= null){
            aux2 = aux2.getNext();
        }
        int nuevaciudad = aux2.getElement().getName()+1;
        nuevaCiudad.setText(Integer.toString(nuevaciudad));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelRound1 = new Clases.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        ciudadConectar = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        nuevaCiudad = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        distancia = new javax.swing.JTextField();
        guardar = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        jPanel2.setBackground(new java.awt.Color(253, 253, 253));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(76, 60, 76));
        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(76, 60, 76));
        jLabel1.setText("Agregar Ciudad");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 190, 80));

        panelRound1.setBackground(new java.awt.Color(76, 60, 76));
        panelRound1.setRoundBottomLeft(10);
        panelRound1.setRoundBottomRight(10);
        panelRound1.setRoundTopLeft(10);
        panelRound1.setRoundTopRight(10);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(253, 253, 253));
        jLabel2.setText("Distancia");
        panelRound1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 190, -1));

        ciudadConectar.setBackground(new java.awt.Color(137, 109, 137));
        ciudadConectar.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        ciudadConectar.setForeground(new java.awt.Color(253, 253, 253));
        ciudadConectar.setBorder(null);
        ciudadConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadConectarActionPerformed(evt);
            }
        });
        panelRound1.add(ciudadConectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, 30));

        jLabel3.setBackground(new java.awt.Color(253, 253, 253));
        jLabel3.setForeground(new java.awt.Color(253, 253, 253));
        jLabel3.setText("Ciudad a agregar:");
        panelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        nuevaCiudad.setForeground(new java.awt.Color(253, 253, 253));
        nuevaCiudad.setText("jLabel4");
        panelRound1.add(nuevaCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(253, 253, 253));
        jLabel5.setText("Ciudad a conectar");
        panelRound1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 190, -1));

        distancia.setBackground(new java.awt.Color(137, 109, 137));
        distancia.setForeground(new java.awt.Color(253, 253, 253));
        distancia.setText("0");
        distancia.setBorder(null);
        distancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distanciaActionPerformed(evt);
            }
        });
        panelRound1.add(distancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 50, -1));

        guardar.setBackground(new java.awt.Color(137, 109, 137));
        guardar.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        guardar.setForeground(new java.awt.Color(253, 253, 253));
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        panelRound1.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 80, -1));

        menu.setBackground(new java.awt.Color(137, 109, 137));
        menu.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        menu.setForeground(new java.awt.Color(253, 253, 253));
        menu.setText("Menu");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        panelRound1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 80, -1));

        jPanel2.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 420, 230));

        jPanel3.setBackground(new java.awt.Color(76, 60, 76));
        jPanel3.setForeground(new java.awt.Color(76, 60, 76));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, 10));

        jPanel4.setBackground(new java.awt.Color(76, 60, 76));
        jPanel4.setForeground(new java.awt.Color(76, 60, 76));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 110, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ciudadConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadConectarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciudadConectarActionPerformed

    private void distanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distanciaActionPerformed
        
    }//GEN-LAST:event_distanciaActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // limite de ciudades 20
        if(ciudadConectar.getItemCount() == 20){
            JOptionPane.showMessageDialog(this, "No puedes tener mas de 20 ciudades");
        }
        else{
            //Si ciudadConectar.getItemCount() != 0 se agrega la ciudad
        try{
            
            String d = distancia.getText();
            float distancia = Float.parseFloat(d);
            //Se crea el objeto ciudad
            Ciudad ciudad = new Ciudad(Integer.parseInt(nuevaCiudad.getText()));
            
            ciudadConectar.addItem("Ciudad: "+nuevaCiudad.getText() );
            int ciudadNueva = Integer.parseInt(nuevaCiudad.getText());
            ciudadNueva ++;
            nuevaCiudad.setText(Integer.toString(ciudadNueva));
            listaciudad.insertFinal(ciudad);
            
            
            Object ciudadaConectar = ciudadConectar.getSelectedItem();
            String ciudadConectar2 = ciudadaConectar.toString();
            char numeroC = ciudadConectar2.charAt(ciudadConectar2.length() - 1);
            int numeroC2 = Character.getNumericValue(numeroC);
                    
            Ciudad ciudadConexion = listaciudad.definirCiudad(numeroC2);
            
            //Se crea el objeto camino
            Camino camino = new Camino(ciudad, ciudadConexion, distancia);
            listacaminos.insertFinal(camino);
            
            //listaciudad.print();
            //listacaminos.print();
        
            
            Global.setListaciudades(listaciudad);
            Global.setListacaminos(listacaminos);
            
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al cargar los datos de tipo: " + e);
        }
        }
    }//GEN-LAST:event_guardarActionPerformed

    // se cierra la ventana y abre la del menu
    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed

        Ventana3 ventana3 = new Ventana3();
        ventana3.setVisible(true);
        this.dispose();
    
    }//GEN-LAST:event_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ciudadConectar;
    private javax.swing.JTextField distancia;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton menu;
    private javax.swing.JLabel nuevaCiudad;
    private Clases.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables
}
